version: '3.7'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
      - db
    ports:
      - "5200:80"
    restart: always
    networks:
      - common_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=p@55w0rd
      - DB_NAME=movie_rent_db
      - ASPNETCORE_ENVIRONMENT=Docker
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p@55w0rd
      - MYSQL_DATABASE=movie_rent_db
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

networks:
  common_network:
volumes:
  datafiles: